FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim AS production

RUN apt update \
    && apt upgrade -y \
    && apt install libturbojpeg0 -y

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

ENV LIBTURBOJPEG=/usr/lib/x86_64-linux-gnu/libturbojpeg.so.0

COPY ./src/cogtiler /app

FROM production as debug
# This enables vscode to do debugging inside container
# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser
