@host=http://localhost:8000

@api_token=xxx
@cog_url=https://api.dataforsyningen.dk/skraafoto_server_test/v1.0/COG_oblique_2021/10km_614_59/1km_6145_592/2021_83_36_1_0020_00003045.tif

@cog_url_token={{cog_url}}?token={{api_token}}

@query_params=url={{cog_url}}&token={{api_token}}


### 
# Returns file info
GET {{host}}/info?{{query_params}} HTTP/1.1

### 
# Returns a single jpeg tile
GET {{host}}/tiles/1/0/1.jpg?{{query_params}} HTTP/1.1

### 
# Returns single jpeg tile (default overflow handling)
GET {{host}}/tiles/0/0/0.jpg?{{query_params}} HTTP/1.1

### 
# Returns single jpeg tile (showing overflow artifacts)
GET {{host}}/tiles/0/0/0.jpg?overflow=pad&{{query_params}} HTTP/1.1

### 
# Returns jpeg tile with artifacts cropped (not 1024x1024)
GET {{host}}/tiles/0/0/0.jpg?overflow=crop&{{query_params}} HTTP/1.1

### 
# Returns jpeg tile with artifacts masked (is 1024x1024)
GET {{host}}/tiles/0/0/0.jpg?overflow=mask&{{query_params}} HTTP/1.1

### 
# Returns html with deepzoom viewer for the image
GET {{host}}/viewer.html?{{query_params}} HTTP/1.1


### 
# Returns thumbnail
GET {{host}}/thumbnail.jpg?{{query_params}} HTTP/1.1

####################################################
### Header auth
####################################################

### 
# Returns file info
GET {{host}}/info?url={{cog_url}} HTTP/1.1
token: {{api_token}}

### 
# Returns a single jpeg tile
GET {{host}}/tiles/1/0/1.jpg?url={{cog_url}} HTTP/1.1
token: {{api_token}}

### 
# Returns single jpeg tile (default overflow handling)
GET {{host}}/tiles/0/0/0.jpg?url={{cog_url}} HTTP/1.1
token: {{api_token}}

### 
# Returns html with deepzoom viewer for the image
GET {{host}}/viewer.html?url={{cog_url}} HTTP/1.1
token: {{api_token}}

### 
# Returns thumbnail
GET {{host}}/thumbnail.jpg?url={{cog_url}} HTTP/1.1
token: {{api_token}}