import math
import time
import sys

from fastapi import FastAPI, Response, Request, HTTPException
from fastapi.param_functions import Depends
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.exception_handlers import http_exception_handler

from aiocogdumper.cog_tiles import COGTiff, Overflow
from aiocogdumper.errors import HTTPError, TIFFError
from settings import Settings

from loguru import logger

from cog import (
    HttpCogClient,
    CogRequest,
)

# Setup of settings and log
settings = Settings()
logger.remove()
logger.add(
    sys.stdout,
    colorize=settings.debug,
    format="<green>{time:HH:mm:ss}</green> | {level} | <level>{message}</level>",
    level="DEBUG" if settings.debug else "INFO",
)
logger.info(f"Starting API using settings: {settings}")

# Instantiate app
app = FastAPI()
cog_client = HttpCogClient()


# Logging as middleware
@app.middleware("http")
async def log_middle(request: Request, call_next):
    start = time.perf_counter()
    response = await call_next(request)
    end = time.perf_counter()
    process_time = f"{(end - start) * 1000:0.1f} ms"
    logger.debug("{} {} {}", request.method, request.url, process_time)
    response.headers["X-Process-Time"] = process_time
    return response


# Startup and shutdown events
@app.on_event("startup")
async def startup_event():
    cog_client.start()


@app.on_event("shutdown")
async def shutdown_event():
    await cog_client.stop()


# Handle http exceptions from upstream server
@app.exception_handler(HTTPError)
async def upstream_http_exception_handler(request, exc: HTTPError):
    logger.warning(f"Upstream HTTP error: {repr(exc)}")
    # Convert to FastApi exception
    exc = HTTPException(502, f"Upstream server returned: [{exc.status}] {exc.message}")
    return await http_exception_handler(request, exc)


# Handle tiff exceptions
@app.exception_handler(TIFFError)
async def upstream_http_exception_handler(request, exc: TIFFError):
    logger.warning(
        f"Tiff error when reading [{request.query_params['url']}]: {repr(exc)}"
    )
    # Convert to FastApi exception
    exc = HTTPException(500, f"Error reading upstream tiff file: {exc.message}")
    return await http_exception_handler(request, exc)


app.mount("/demo", StaticFiles(directory="demo_client"), name="demo")

########################################################################################
# cog endpoint generally follows this form:

# Return binary content from fastapi https://stackoverflow.com/a/67497103
"""
@app.get(
    "/cog",
    # Set what the media type will be in the autogenerated OpenAPI specification.
    # fastapi.tiangolo.com/advanced/additional-responses/#additional-media-types-for-the-main-response
    responses={200: {"content": {"image/jpeg": {}}}},
    # Prevent FastAPI from adding "application/json" as an additional
    # response media type in the autogenerated OpenAPI specification.
    # https://github.com/tiangolo/fastapi/issues/3258
    response_class=Response,
)
async def get_cog(
    z: int,
    x: int,
    y: int,
    overflow: Overflow = Overflow.Pad,
    cog: COGTiff = Depends(cog_client.cog_from_query_param),
):
    return await cog_client.get_tile_response(cog, z, x, y, overflow)
"""

########################################################################################
# image metadata


@app.get("/info")
async def get_info(cog: COGTiff = Depends(cog_client.cog_from_query_param)):
    return await cog.get_info(0)


########################################################################################
# thumbnail endpoint


@app.get(
    "/thumbnail.jpg",
    responses={200: {"content": {"image/jpeg": {}}}},
    response_class=Response,
)
async def get_thumbnail(cog: COGTiff = Depends(cog_client.cog_from_query_param)):
    info = await cog.get_info(0)
    max_zoom = info["overviews"]
    return await cog_client.get_tile_response(
        cog, max_zoom, 0, 0, overflow=Overflow.Crop
    )


########################################################################################
# xyz tiles endpoint
@app.get(
    "/tiles/{z}/{x}/{y}.jpg",
    responses={200: {"content": {"image/jpeg": {}}}},
    response_class=Response,
)
async def get_tile_from_xyz(
    z: int,
    x: int,
    y: int,
    overflow: Overflow = Overflow.Mask,
    cog: COGTiff = Depends(cog_client.cog_from_query_param),
):
    info = await cog.get_info(0)
    zoomlevels = info["overviews"] + 1
    cog_z = zoomlevels - z - 1
    return await cog_client.get_tile_response(cog, cog_z, x, y, overflow)


########################################################################################
# deepzoom
@app.get(
    "/deepzoom.dzi",
    responses={200: {"content": {"application/xml": {}}}},
    response_class=Response,
)
async def get_deepzoom_xml(cog: COGTiff = Depends(cog_client.cog_from_query_param)):
    info = await cog.get_info(0)
    xml = f"""<?xml version="1.0" encoding="utf-8"?>
                    <Image TileSize="{info["tile_width"]}" Rotation="0" Overlap="0" Format="jpg" ServerFormat="Default" xmlns="http://schemas.microsoft.com/deepzoom/2009">
                        <Size Width="{info["width"]}" Height="{info["height"]}"  />
                    </Image>"""
    return Response(content=xml, media_type="application/xml")


@app.get(
    "/deepzoom_files/{z}/{tilename}",
    responses={200: {"content": {"image/jpeg": {}}}},
    response_class=Response,
)
async def get_deepzoom_tile(
    z: int, tilename: str, cog: COGTiff = Depends(cog_client.cog_from_query_param)
):
    # TODO: regex på tile i FastAPI. TROR det er ("x_y.jpg")
    x, y = map(int, tilename[:-4].split("_"))
    # DeepZoom uses inverted z
    info = await cog.get_info(0)
    # https://github.com/openzoom/deepzoom.py/blob/master/deepzoom/__init__.py#L121
    max_dimension = max(info["width"], info["height"])
    num_levels = int(math.ceil(math.log(max_dimension, 2))) + 1
    cog_z = num_levels - z - 1
    # DeepZoom apparantly crops overflow away from tiles
    return await cog_client.get_tile_response(cog, cog_z, x, y, Overflow.Crop)


########################################################################################
# html viewer


@app.get(
    "/viewer.html",
    response_class=HTMLResponse,
)
async def get_html_viewer(cog_req: CogRequest = Depends(CogRequest)):
    token = cog_req.get_token()
    token_param = f"&token={token}" if token else ""
    html = f"""
<html>
<head>
<title>{cog_req.url}</title>
</head>
<body>
    <div id="openseadragon1" style="width: 1024px; height: 800px;"></div>
    <div id="metadata" style="width: 1024px; background-color: gainsboro;"></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/openseadragon/3.0.0/openseadragon.min.js"></script>
    <script type="text/javascript">
        var encoded_url = encodeURIComponent("{cog_req.url}");
        var viewer = OpenSeadragon({{
            id: "openseadragon1",
            prefixUrl: "https://cdnjs.cloudflare.com/ajax/libs/openseadragon/3.0.0/images/",
            tileSources: "./deepzoom.dzi?url=" + encoded_url + "{token_param}"
        }});
    </script>
</body>
</html>"""
    return HTMLResponse(html)


########################################################################################
# helper methods
